#!/usr/bin/env python3
"""Download Simple Icons (CC0) and write Sources/Portbar/Icons/BrandPaths.swift."""
import re, sys, urllib.request, pathlib

SLUGS = """nextdotjs vite convex bun nodedotjs deno astro nuxt remix svelte expo react storybook
postgresql redis docker python django flask fastapi rubyonrails go rust cloudflare vercel turborepo
webpack prisma drizzle supabase mongodb mysql nginx esbuild typescript vitest jest hono angular
vuedotjs electron tauri php laravel elixir ollama sqlite
flutter swift kotlin dart""".split()

out = ["// Generated by scripts/gen-icons.py from Simple Icons (CC0). Do not edit.", "",
       "enum BrandPaths {", "    static let all: [String: String] = ["]
for slug in SLUGS:
    svg = urllib.request.urlopen(f"https://cdn.jsdelivr.net/npm/simple-icons@latest/icons/{slug}.svg").read().decode()
    d = re.search(r'<path d="([^"]+)"', svg).group(1)
    out.append(f'        "{slug}": "{d}",')
out += ["    ]", "}", ""]
dest = pathlib.Path(__file__).resolve().parent.parent / "Sources/Portbar/Icons/BrandPaths.swift"
dest.write_text("\n".join(out))
print(f"wrote {len(SLUGS)} icons to {dest}")
